unload_default_env() {
  unset CFME_CONFIG_DIR
  unset CFME_PROMPT_DIR
  unset CFME_PROMPT_TYPE
  unset CFME_DEFAULT_PROMPT_FILE
  unset CFME_DEFAULT_PROMPT_VARIABLES_FILE
  unset CFME_SILENT_MODE
  unset CFME_DEFAULT_PROMPT_FILE_FETCH_URL
  unset CFME_DEFAULT_PROMPT_VARIABLES_FILE_FETCH_URL
  unset CFME_NO_SPINNER
}
